# Generated by Django 5.0.4 on 2024-05-30 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to='datasources/', verbose_name='Datasource file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Datasource',
                'verbose_name_plural': 'Datasources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RenderedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='renders/', verbose_name='Rendered file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.datasource')),
            ],
            options={
                'verbose_name': 'Rendered File',
                'verbose_name_plural': 'Rendered Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Template file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='renderedfile',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.template'),
        ),
    ]
