# Generated by Django 5.0.4 on 2024-05-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datasource_renderedfile_template_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedfile',
            name='sheet',
            field=models.CharField(default='Sheet2', max_length=255),
        ),
    ]
